In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4]
arr = np.array(lst)

In [3]:
print(type(lst))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [7]:
import time
start = time.time()
lst_1 = [1,2,3,4]
lst_2 = [4,5,6,7]
x = []
for i in range(len(lst_1)):
    x.append(lst_1[i] + lst_2[i]) 
print(x)
print("time take: ", (time.time()-start)*1000)

[5, 7, 9, 11]
time take:  2.2268295288085938


In [8]:
start = time.time()
lst_1 = [1,2,3,4]
lst_2 = [4,5,6,7]
x = [(x+y) for x,y in zip(lst_1, lst_2)]
print(x)
print("time take: ", (time.time()-start)*1000)


[5, 7, 9, 11]
time take:  1.1997222900390625


In [10]:
lst_1 = [1,2,3,4]
lst_2 = [4,5,6,7]
start = time.time()
np.array(lst_1) + np.array(lst_2)
print("time take: ", (time.time()-start)*1000)

time take:  0.15592575073242188


In [11]:
lst_1 = [1,2,3,4]
lst_2 = [4,5,6,7]
lst_1 + lst_2

[1, 2, 3, 4, 4, 5, 6, 7]

In [12]:
np.array(lst) + np.array(lst_1)

array([2, 4, 6, 8])

In [13]:
lst = [*range(5)]
lst

[0, 1, 2, 3, 4]

In [14]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [15]:
arr = np.arange(5)
print(arr.dtype)

int64


In [16]:
arr.shape

(5,)

In [17]:
arr_2d = np.array([[1,2,3,4], [1,2,3,4]])
arr_2d

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [18]:
arr_2d.shape

(2, 4)

In [19]:
np.array(["hello"]).dtype

dtype('<U5')

In [20]:
a_size = (16, 16)
arr_0 = np.zeros(shape=a_size)
arr_0

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [21]:
arr_0 + 1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,

In [22]:
arr_0.shape

(16, 16)

In [23]:
np.zeros(shape=(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones(shape=(3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.full((3,3), "hello")

array([['hello', 'hello', 'hello'],
       ['hello', 'hello', 'hello'],
       ['hello', 'hello', 'hello']], dtype='<U5')

In [26]:
arr = np.random.randn(3,3)

In [28]:
arr = 3 + 1 *  np.random.randn(3,3)
arr

array([[3.99333089, 3.97072009, 2.84377374],
       [4.5474424 , 2.67513797, 1.91061033],
       [3.23999972, 1.91118321, 3.9066278 ]])

In [29]:
arr.mean()

3.222091793463804

In [30]:
np.random.rand(3,3)

array([[0.72699097, 0.35832553, 0.43387487],
       [0.12639266, 0.6772051 , 0.15981666],
       [0.99055368, 0.36568073, 0.38020517]])

In [31]:
arr = np.random.randint(low=1, high=20, size=(5,5,3))
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[12 18 19]
  [ 3  8  6]
  [ 2 10 19]
  [ 7  3  3]
  [18  3 18]]

 [[ 5 18  2]
  [ 6  8 19]
  [18  7  1]
  [17  3 12]
  [ 2  2 12]]

 [[ 2  3 14]
  [16 17  9]
  [19 19  5]
  [10  9 19]
  [ 1  1 17]]

 [[14  7  2]
  [ 5 14 11]
  [10 19 15]
  [16 12 14]
  [ 8 16 11]]

 [[ 1 11 11]
  [ 4 12  3]
  [ 6  2 11]
  [ 7 17  3]
  [17  2  9]]]
(5, 5, 3)
3
75


In [32]:
np.arange(0, 12, 2).shape

(6,)